async page => {
  const started = Date.now();
  const scenes = [];
  const caption = async (title, detail, seconds = 12) => {
    scenes.push(title);
    await page.evaluate(({title,detail}) => {
      let box = document.getElementById('demo-caption');
      if (!box) { box = document.createElement('aside'); box.id = 'demo-caption'; document.body.append(box); }
      box.style.cssText = 'position:fixed;z-index:9999;bottom:18px;left:5%;width:90%;box-sizing:border-box;padding:16px 24px;background:#142b35;color:white;border:2px solid #ef8b58;border-radius:12px;font:18px/1.5 system-ui;box-shadow:0 8px 30px #0004;pointer-events:none';
      box.replaceChildren();
      const heading = document.createElement('strong');heading.textContent=title;heading.style.cssText='display:block;font-size:22px';
      const text = document.createElement('div');text.textContent=detail;box.append(heading,text);
    }, {title,detail});
    await page.waitForTimeout(seconds * 1000);
  };
  page.on('dialog', dialog => dialog.accept());
  await page.setViewportSize({width:1440,height:960});
  await page.goto('http://127.0.0.1:8211/');
  await page.locator('#demo-button').click();
  await caption('Shiftproof — catch rota gaps, share only what changed.', 'An offline organiser workspace. This campus repair-day example and all its volunteers are fictional.');
  await page.locator('.metrics').scrollIntoViewIfNeeded();
  await caption('One revision. Two consequences.', 'The revised rota has one uncovered duty and one double booking. Four shifts changed between the two versions.');
  await page.locator('.shift-row[data-shift-id="welcome"]').click();
  await page.locator('#shift-detail').scrollIntoViewIfNeeded();
  await caption('See the source of the problem.', 'The welcome desk moved from 08:00–09:30 to 08:30–10:00. Alex also starts setting up tables at 09:30.');
  await page.locator('.shift-row[data-shift-id="setup"]').click();
  await page.locator('#assignment-list').getByLabel('Alex',{exact:true}).uncheck();
  await page.locator('#assignment-list').getByLabel('Jules',{exact:true}).check();
  await page.locator('#apply-assignment').click();
  await caption('Review a repair; keep the organiser in control.', 'Jules replaces Alex at setup. The loaded rota shows no overlap. A real organiser would still confirm availability and agreement.');
  await page.locator('.shift-row[data-shift-id="donations"]').click();
  await page.locator('#assignment-list').getByLabel('Alex',{exact:true}).check();
  await page.locator('#apply-assignment').click();
  await page.locator('.metrics').scrollIntoViewIfNeeded();
  await caption('Fill the gap and recompute the whole plan.', 'Alex can cover the donated-items shift in this example. Both checks clear immediately; adjacent shifts are treated consistently.');
  await page.locator('#person-select').selectOption('Alex');
  await page.locator('#card-preview').scrollIntoViewIfNeeded();
  await caption('Give Alex a personal before-and-after card.', 'The later welcome desk, removed setup duty and new sorting duty appear together. Other volunteers’ names stay out of this card.');
  await page.evaluate(()=>document.getElementById('demo-caption')?.remove());
  await page.emulateMedia({media:'print'});
  await page.evaluate(()=>scrollTo(0,0));
  await page.pdf({path:'../../services/shiftproof/artifacts/demo-card.pdf',format:'A4',printBackground:true});
  await page.waitForTimeout(12_000);
  scenes.push('Actual selected-card print layout and PDF');
  await page.emulateMedia({media:'screen',reducedMotion:'reduce'});
  await page.locator('#download-csv').scrollIntoViewIfNeeded();
  const csv = page.waitForEvent('download');await page.locator('#download-csv').click();await (await csv).saveAs('../../services/shiftproof/artifacts/demo-rota.csv');
  const json = page.waitForEvent('download');await page.locator('#download-json').click();await (await json).saveAs('../../services/shiftproof/artifacts/demo-review.json');
  await caption('Keep a portable, repaired review.', 'Download the revised CSV for the rota and JSON to reopen both versions. Imports are validated; unresolved checks are flagged before sharing.');
  await page.evaluate(()=>document.querySelector('details').open=true);
  await page.locator('#review-file').setInputFiles('../../services/shiftproof/artifacts/demo-review.json');
  await page.locator('.metrics').scrollIntoViewIfNeeded();
  await caption('Reopen the exported review.', 'The same assignments and checks are restored from the actual downloaded JSON. No account, API key or backend is needed.');
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;});
  await page.context().setOffline(true);
  await page.reload();
  await page.locator('.metrics').scrollIntoViewIfNeeded();
  await caption('Continue after the connection disappears.', 'This is an actual offline reload after the app was cached. The local review stays available on this device.');
  await page.context().setOffline(false);
  await page.setViewportSize({width:390,height:844});
  await page.locator('#person-select').selectOption('Alex');
  await page.locator('#card-preview').scrollIntoViewIfNeeded();
  await page.evaluate(()=>document.getElementById('demo-caption')?.remove());
  await page.waitForTimeout(12_000);scenes.push('390px mobile change card');
  await page.setViewportSize({width:1440,height:960});
  await page.evaluate(()=>scrollTo(0,0));
  await caption('A complete handoff, with a small footprint.', 'Compare → repair → share. Original browser-only prototype, AI-assisted development, fictional demonstration data.', 15);
  await page.evaluate(()=>document.getElementById('demo-caption')?.remove());
  return {recorded_at:new Date().toISOString(),duration_seconds:(Date.now()-started)/1000,scenes,data:'fictional campus repair day',offline_reload:true};
}
